{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "cc29f5ba-eedb-43ad-a00c-2df0a27962cc",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: openmeteo-requests in C:\\Users\\adeel\\anaconda3\\envs\\Kaggledataanalysis\\Lib\\site-packages (1.7.5)\n",
      "Requirement already satisfied: niquests>=3.15.2 in C:\\Users\\adeel\\anaconda3\\envs\\Kaggledataanalysis\\Lib\\site-packages (from openmeteo-requests) (3.18.6)\n",
      "Requirement already satisfied: openmeteo-sdk>=1.22.0 in C:\\Users\\adeel\\anaconda3\\envs\\Kaggledataanalysis\\Lib\\site-packages (from openmeteo-requests) (1.26.0)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in C:\\Users\\adeel\\anaconda3\\envs\\Kaggledataanalysis\\Lib\\site-packages (from niquests>=3.15.2->openmeteo-requests) (3.4.4)\n",
      "Requirement already satisfied: urllib3-future<3,>=2.13.903 in C:\\Users\\adeel\\anaconda3\\envs\\Kaggledataanalysis\\Lib\\site-packages (from niquests>=3.15.2->openmeteo-requests) (2.19.909)\n",
      "Requirement already satisfied: wassima<3,>=1.0.1 in C:\\Users\\adeel\\anaconda3\\envs\\Kaggledataanalysis\\Lib\\site-packages (from niquests>=3.15.2->openmeteo-requests) (2.0.6)\n",
      "Requirement already satisfied: h11<1.0.0,>=0.11.0 in C:\\Users\\adeel\\anaconda3\\envs\\Kaggledataanalysis\\Lib\\site-packages (from urllib3-future<3,>=2.13.903->niquests>=3.15.2->openmeteo-requests) (0.16.0)\n",
      "Requirement already satisfied: jh2<6.0.0,>=5.0.3 in C:\\Users\\adeel\\anaconda3\\envs\\Kaggledataanalysis\\Lib\\site-packages (from urllib3-future<3,>=2.13.903->niquests>=3.15.2->openmeteo-requests) (5.0.11)\n",
      "Requirement already satisfied: qh3<2.0.0,>=1.5.4 in C:\\Users\\adeel\\anaconda3\\envs\\Kaggledataanalysis\\Lib\\site-packages (from urllib3-future<3,>=2.13.903->niquests>=3.15.2->openmeteo-requests) (1.7.1)\n",
      "Requirement already satisfied: flatbuffers==25.9.23 in C:\\Users\\adeel\\anaconda3\\envs\\Kaggledataanalysis\\Lib\\site-packages (from openmeteo-sdk>=1.22.0->openmeteo-requests) (25.9.23)\n",
      "Requirement already satisfied: requests-cache in C:\\Users\\adeel\\anaconda3\\envs\\Kaggledataanalysis\\Lib\\site-packages (1.3.1)\n",
      "Requirement already satisfied: retry-requests in C:\\Users\\adeel\\anaconda3\\envs\\Kaggledataanalysis\\Lib\\site-packages (2.0.0)\n",
      "Requirement already satisfied: numpy in C:\\Users\\adeel\\anaconda3\\envs\\Kaggledataanalysis\\Lib\\site-packages (2.4.4)\n",
      "Requirement already satisfied: pandas in C:\\Users\\adeel\\anaconda3\\envs\\Kaggledataanalysis\\Lib\\site-packages (2.3.3)\n",
      "Collecting streamlit\n",
      "  Downloading streamlit-1.56.0-py3-none-any.whl.metadata (9.8 kB)\n",
      "Requirement already satisfied: attrs>=21.2 in C:\\Users\\adeel\\anaconda3\\envs\\Kaggledataanalysis\\Lib\\site-packages (from requests-cache) (26.1.0)\n",
      "Requirement already satisfied: cattrs>=22.2 in C:\\Users\\adeel\\anaconda3\\envs\\Kaggledataanalysis\\Lib\\site-packages (from requests-cache) (26.1.0)\n",
      "Requirement already satisfied: platformdirs>=2.5 in C:\\Users\\adeel\\anaconda3\\envs\\Kaggledataanalysis\\Lib\\site-packages (from requests-cache) (4.9.4)\n",
      "Requirement already satisfied: requests>=2.22 in C:\\Users\\adeel\\anaconda3\\envs\\Kaggledataanalysis\\Lib\\site-packages (from requests-cache) (2.33.1)\n",
      "Requirement already satisfied: url-normalize>=2.0 in C:\\Users\\adeel\\anaconda3\\envs\\Kaggledataanalysis\\Lib\\site-packages (from requests-cache) (2.2.1)\n",
      "Requirement already satisfied: urllib3>=1.25.5 in C:\\Users\\adeel\\anaconda3\\envs\\Kaggledataanalysis\\Lib\\site-packages (from requests-cache) (2.6.3)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in C:\\Users\\adeel\\anaconda3\\envs\\Kaggledataanalysis\\Lib\\site-packages (from pandas) (2.9.0.post0)\n",
      "Requirement already satisfied: pytz>=2020.1 in C:\\Users\\adeel\\anaconda3\\envs\\Kaggledataanalysis\\Lib\\site-packages (from pandas) (2026.1.post1)\n",
      "Requirement already satisfied: tzdata>=2022.7 in C:\\Users\\adeel\\anaconda3\\envs\\Kaggledataanalysis\\Lib\\site-packages (from pandas) (2026.1)\n",
      "Collecting altair!=5.4.0,!=5.4.1,<7,>=4.0 (from streamlit)\n",
      "  Downloading altair-6.0.0-py3-none-any.whl.metadata (11 kB)\n",
      "Requirement already satisfied: blinker<2,>=1.5.0 in C:\\Users\\adeel\\anaconda3\\envs\\Kaggledataanalysis\\Lib\\site-packages (from streamlit) (1.9.0)\n",
      "Requirement already satisfied: cachetools<8,>=5.5 in C:\\Users\\adeel\\anaconda3\\envs\\Kaggledataanalysis\\Lib\\site-packages (from streamlit) (7.0.5)\n",
      "Requirement already satisfied: click<9,>=7.0 in C:\\Users\\adeel\\anaconda3\\envs\\Kaggledataanalysis\\Lib\\site-packages (from streamlit) (8.3.2)\n",
      "Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in C:\\Users\\adeel\\anaconda3\\envs\\Kaggledataanalysis\\Lib\\site-packages (from streamlit) (3.1.46)\n",
      "Requirement already satisfied: packaging>=20 in C:\\Users\\adeel\\anaconda3\\envs\\Kaggledataanalysis\\Lib\\site-packages (from streamlit) (26.0)\n",
      "Requirement already satisfied: pillow<13,>=7.1.0 in C:\\Users\\adeel\\anaconda3\\envs\\Kaggledataanalysis\\Lib\\site-packages (from streamlit) (12.2.0)\n",
      "Collecting pydeck<1,>=0.8.0b4 (from streamlit)\n",
      "  Downloading pydeck-0.9.2-py2.py3-none-any.whl.metadata (4.2 kB)\n",
      "Requirement already satisfied: protobuf<8,>=3.20 in C:\\Users\\adeel\\anaconda3\\envs\\Kaggledataanalysis\\Lib\\site-packages (from streamlit) (6.33.6)\n",
      "Requirement already satisfied: pyarrow>=7.0 in C:\\Users\\adeel\\anaconda3\\envs\\Kaggledataanalysis\\Lib\\site-packages (from streamlit) (23.0.1)\n",
      "Collecting tenacity<10,>=8.1.0 (from streamlit)\n",
      "  Downloading tenacity-9.1.4-py3-none-any.whl.metadata (1.2 kB)\n",
      "Collecting toml<2,>=0.10.1 (from streamlit)\n",
      "  Downloading toml-0.10.2-py2.py3-none-any.whl.metadata (7.1 kB)\n",
      "Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in C:\\Users\\adeel\\anaconda3\\envs\\Kaggledataanalysis\\Lib\\site-packages (from streamlit) (6.5.5)\n",
      "Requirement already satisfied: typing-extensions<5,>=4.10.0 in C:\\Users\\adeel\\anaconda3\\envs\\Kaggledataanalysis\\Lib\\site-packages (from streamlit) (4.15.0)\n",
      "Collecting watchdog<7,>=2.1.5 (from streamlit)\n",
      "  Downloading watchdog-6.0.0-py3-none-win_amd64.whl.metadata (44 kB)\n",
      "Requirement already satisfied: jinja2 in C:\\Users\\adeel\\anaconda3\\envs\\Kaggledataanalysis\\Lib\\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.1.6)\n",
      "Requirement already satisfied: jsonschema>=3.0 in C:\\Users\\adeel\\anaconda3\\envs\\Kaggledataanalysis\\Lib\\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (4.25.1)\n",
      "Requirement already satisfied: narwhals>=1.27.1 in C:\\Users\\adeel\\anaconda3\\envs\\Kaggledataanalysis\\Lib\\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2.19.0)\n",
      "Requirement already satisfied: colorama in C:\\Users\\adeel\\anaconda3\\envs\\Kaggledataanalysis\\Lib\\site-packages (from click<9,>=7.0->streamlit) (0.4.6)\n",
      "Requirement already satisfied: gitdb<5,>=4.0.1 in C:\\Users\\adeel\\anaconda3\\envs\\Kaggledataanalysis\\Lib\\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)\n",
      "Requirement already satisfied: smmap<6,>=3.0.1 in C:\\Users\\adeel\\anaconda3\\envs\\Kaggledataanalysis\\Lib\\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.3)\n",
      "Requirement already satisfied: charset_normalizer<4,>=2 in C:\\Users\\adeel\\anaconda3\\envs\\Kaggledataanalysis\\Lib\\site-packages (from requests>=2.22->requests-cache) (3.4.4)\n",
      "Requirement already satisfied: idna<4,>=2.5 in C:\\Users\\adeel\\anaconda3\\envs\\Kaggledataanalysis\\Lib\\site-packages (from requests>=2.22->requests-cache) (3.11)\n",
      "Requirement already satisfied: certifi>=2023.5.7 in C:\\Users\\adeel\\anaconda3\\envs\\Kaggledataanalysis\\Lib\\site-packages (from requests>=2.22->requests-cache) (2026.1.4)\n",
      "Requirement already satisfied: MarkupSafe>=2.0 in C:\\Users\\adeel\\anaconda3\\envs\\Kaggledataanalysis\\Lib\\site-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.0.2)\n",
      "Requirement already satisfied: jsonschema-specifications>=2023.03.6 in C:\\Users\\adeel\\anaconda3\\envs\\Kaggledataanalysis\\Lib\\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2025.9.1)\n",
      "Requirement already satisfied: referencing>=0.28.4 in C:\\Users\\adeel\\anaconda3\\envs\\Kaggledataanalysis\\Lib\\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.37.0)\n",
      "Requirement already satisfied: rpds-py>=0.7.1 in C:\\Users\\adeel\\anaconda3\\envs\\Kaggledataanalysis\\Lib\\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.28.0)\n",
      "Requirement already satisfied: six>=1.5 in C:\\Users\\adeel\\anaconda3\\envs\\Kaggledataanalysis\\Lib\\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)\n",
      "Downloading streamlit-1.56.0-py3-none-any.whl (9.1 MB)\n",
      "   ---------------------------------------- 0.0/9.1 MB ? eta -:--:--\n",
      "   --------------- ------------------------ 3.4/9.1 MB 18.3 MB/s eta 0:00:01\n",
      "   ----------------------------------- ---- 8.1/9.1 MB 20.1 MB/s eta 0:00:01\n",
      "   ---------------------------------------- 9.1/9.1 MB 18.3 MB/s  0:00:00\n",
      "Downloading altair-6.0.0-py3-none-any.whl (795 kB)\n",
      "   ---------------------------------------- 0.0/795.4 kB ? eta -:--:--\n",
      "   ---------------------------------------- 795.4/795.4 kB 18.5 MB/s  0:00:00\n",
      "Downloading pydeck-0.9.2-py2.py3-none-any.whl (11.3 MB)\n",
      "   ---------------------------------------- 0.0/11.3 MB ? eta -:--:--\n",
      "   ------------ --------------------------- 3.7/11.3 MB 17.3 MB/s eta 0:00:01\n",
      "   ----------------------------- ---------- 8.4/11.3 MB 19.7 MB/s eta 0:00:01\n",
      "   ---------------------------------------- 11.3/11.3 MB 19.2 MB/s  0:00:00\n",
      "Downloading tenacity-9.1.4-py3-none-any.whl (28 kB)\n",
      "Downloading toml-0.10.2-py2.py3-none-any.whl (16 kB)\n",
      "Downloading watchdog-6.0.0-py3-none-win_amd64.whl (79 kB)\n",
      "Installing collected packages: watchdog, toml, tenacity, pydeck, altair, streamlit\n",
      "\n",
      "   ------------- -------------------------- 2/6 [tenacity]\n",
      "   -------------------- ------------------- 3/6 [pydeck]\n",
      "   -------------------------- ------------- 4/6 [altair]\n",
      "   -------------------------- ------------- 4/6 [altair]\n",
      "   -------------------------- ------------- 4/6 [altair]\n",
      "   -------------------------- ------------- 4/6 [altair]\n",
      "   -------------------------- ------------- 4/6 [altair]\n",
      "   --------------------------------- ------ 5/6 [streamlit]\n",
      "   --------------------------------- ------ 5/6 [streamlit]\n",
      "   --------------------------------- ------ 5/6 [streamlit]\n",
      "   --------------------------------- ------ 5/6 [streamlit]\n",
      "   --------------------------------- ------ 5/6 [streamlit]\n",
      "   --------------------------------- ------ 5/6 [streamlit]\n",
      "   --------------------------------- ------ 5/6 [streamlit]\n",
      "   --------------------------------- ------ 5/6 [streamlit]\n",
      "   --------------------------------- ------ 5/6 [streamlit]\n",
      "   --------------------------------- ------ 5/6 [streamlit]\n",
      "   --------------------------------- ------ 5/6 [streamlit]\n",
      "   --------------------------------- ------ 5/6 [streamlit]\n",
      "   --------------------------------- ------ 5/6 [streamlit]\n",
      "   ---------------------------------------- 6/6 [streamlit]\n",
      "\n",
      "Successfully installed altair-6.0.0 pydeck-0.9.2 streamlit-1.56.0 tenacity-9.1.4 toml-0.10.2 watchdog-6.0.0\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2026-04-20 14:05:43.500 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 14:05:43.501 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 14:05:44.256 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run C:\\Users\\adeel\\anaconda3\\envs\\Kaggledataanalysis\\Lib\\site-packages\\ipykernel_launcher.py [ARGUMENTS]\n",
      "2026-04-20 14:05:44.257 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 14:05:44.258 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 14:05:44.259 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 14:05:44.259 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 14:05:44.260 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 14:05:44.262 No runtime found, using MemoryCacheStorageManager\n",
      "2026-04-20 14:05:44.264 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 14:05:44.265 No runtime found, using MemoryCacheStorageManager\n",
      "2026-04-20 14:05:44.266 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 14:05:45.910 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 14:05:45.911 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 14:05:45.911 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 14:05:45.912 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 14:05:45.913 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 14:05:45.913 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 14:05:45.914 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 14:05:45.915 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 14:05:45.916 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 14:05:45.917 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 14:05:45.917 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 14:05:45.918 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 14:05:45.919 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 14:05:45.920 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 14:05:45.921 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 14:05:45.922 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 14:05:45.923 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 14:05:45.924 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 14:05:45.925 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 14:05:45.926 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 14:05:45.926 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 14:05:45.927 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 14:05:45.928 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 14:05:45.929 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 14:05:45.930 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 14:05:45.930 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 14:05:45.931 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 14:05:46.514 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 14:05:46.515 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 14:05:46.515 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 14:05:46.516 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 14:05:46.517 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 14:05:46.518 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 14:05:46.518 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 14:05:46.519 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 14:05:46.520 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 14:05:46.526 Please replace `use_container_width` with `width`.\n",
      "\n",
      "`use_container_width` will be removed after 2025-12-31.\n",
      "\n",
      "For `use_container_width=True`, use `width='stretch'`. For `use_container_width=False`, use `width='content'`.\n",
      "2026-04-20 14:05:46.529 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 14:05:46.529 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 14:05:46.530 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 14:05:46.531 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 14:05:46.532 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 14:05:46.532 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 14:05:46.533 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 14:05:46.534 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 14:05:46.535 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 14:05:46.553 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 14:05:46.553 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-04-20 14:05:46.554 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "DeltaGenerator()"
      ]
     },
     "execution_count": 1,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "!pip install openmeteo-requests\n",
    "!pip install requests-cache retry-requests numpy pandas streamlit\n",
    "\n",
    "import streamlit as st\n",
    "import openmeteo_requests\n",
    "import pandas as pd\n",
    "import requests_cache\n",
    "from retry_requests import retry\n",
    "\n",
    "st.set_page_config(page_title=\"Budapest Weather Anomaly Dashboard\", layout=\"wide\")\n",
    "st.title(\"🌦️ Budapest Weather Anomaly Dashboard\")\n",
    "st.caption(\"Live hourly data from Open-Meteo — anomalies detected using Z-score (threshold: ±3σ)\")\n",
    "\n",
    "@st.cache_data(ttl=3600)\n",
    "def load_data():\n",
    "    cache_session = requests_cache.CachedSession('.cache', expire_after=3600)\n",
    "    retry_session = retry(cache_session, retries=5, backoff_factor=0.2)\n",
    "    openmeteo = openmeteo_requests.Client(session=retry_session)\n",
    "\n",
    "    url = \"https://archive-api.open-meteo.com/v1/archive\"\n",
    "    params = {\n",
    "        \"latitude\": 47.4979,\n",
    "        \"longitude\": 19.0402,\n",
    "        \"start_date\": \"2020-01-01\",\n",
    "        \"end_date\": pd.Timestamp.today().strftime(\"%Y-%m-%d\"),\n",
    "        \"hourly\": [\"temperature_2m\", \"relative_humidity_2m\", \"precipitation\", \"wind_speed_10m\", \"apparent_temperature\"],\n",
    "        \"timezone\": \"Europe/Budapest\"\n",
    "    }\n",
    "\n",
    "    responses = openmeteo.weather_api(url, params=params)\n",
    "    response = responses[0]\n",
    "    hourly = response.Hourly()\n",
    "\n",
    "    df = pd.DataFrame({\n",
    "        \"date\":                 pd.date_range(start=pd.to_datetime(hourly.Time(), unit=\"s\", utc=True),\n",
    "                                              end=pd.to_datetime(hourly.TimeEnd(), unit=\"s\", utc=True),\n",
    "                                              freq=pd.Timedelta(seconds=hourly.Interval()), inclusive=\"left\"),\n",
    "        \"temperature_2m\":       hourly.Variables(0).ValuesAsNumpy(),\n",
    "        \"relative_humidity_2m\": hourly.Variables(1).ValuesAsNumpy(),\n",
    "        \"precipitation\":        hourly.Variables(2).ValuesAsNumpy(),\n",
    "        \"wind_speed_10m\":       hourly.Variables(3).ValuesAsNumpy(),\n",
    "        \"apparent_temperature\": hourly.Variables(4).ValuesAsNumpy(),\n",
    "    })\n",
    "\n",
    "    df[\"date\"] = df[\"date\"].dt.tz_convert(\"Europe/Budapest\")\n",
    "    df[\"Month\"] = df[\"date\"].dt.month\n",
    "    df[\"Hour\"]  = df[\"date\"].dt.hour\n",
    "\n",
    "    for col, label in [\n",
    "        (\"temperature_2m\",       \"temp\"),\n",
    "        (\"relative_humidity_2m\", \"humidity\"),\n",
    "        (\"precipitation\",        \"precipitation\"),\n",
    "        (\"wind_speed_10m\",       \"wind_speed\"),\n",
    "        (\"apparent_temperature\", \"apparent_temperature\"),\n",
    "    ]:\n",
    "        df[f\"expected_mean_{label}\"] = df.groupby([\"Month\", \"Hour\"])[col].transform(\"mean\")\n",
    "        df[f\"expected_std_{label}\"]  = df.groupby([\"Month\", \"Hour\"])[col].transform(\"std\")\n",
    "        df[f\"anomaly_score_{label}\"] = (df[col] - df[f\"expected_mean_{label}\"]) / df[f\"expected_std_{label}\"]\n",
    "\n",
    "    anomaly_cols = [f\"anomaly_score_{l}\" for l in [\"temp\", \"humidity\", \"precipitation\", \"wind_speed\", \"apparent_temperature\"]]\n",
    "    df[\"is_anomaly\"] = (df[anomaly_cols].abs() > 3).any(axis=1)\n",
    "\n",
    "    return df\n",
    "\n",
    "with st.spinner(\"Loading live data...\"):\n",
    "    df = load_data()\n",
    "\n",
    "# --- KPI Row ---\n",
    "latest = df.iloc[-1]\n",
    "total_anomalies = df[\"is_anomaly\"].sum()\n",
    "anomaly_rate = df[\"is_anomaly\"].mean() * 100\n",
    "\n",
    "col1, col2, col3, col4, col5 = st.columns(5)\n",
    "col1.metric(\"🌡️ Temperature\",    f\"{latest['temperature_2m']:.1f} °C\")\n",
    "col2.metric(\"💧 Humidity\",        f\"{latest['relative_humidity_2m']:.0f} %\")\n",
    "col3.metric(\"🌧️ Precipitation\",   f\"{latest['precipitation']:.1f} mm\")\n",
    "col4.metric(\"💨 Wind Speed\",      f\"{latest['wind_speed_10m']:.1f} km/h\")\n",
    "col5.metric(\"🚨 Anomaly Rate\",    f\"{anomaly_rate:.2f} %\")\n",
    "\n",
    "st.divider()\n",
    "\n",
    "# --- Last 72 Hours ---\n",
    "st.subheader(\"📈 Last 72 Hours — Temperature\")\n",
    "last_72 = df.tail(72).copy()\n",
    "last_72[\"color\"] = last_72[\"is_anomaly\"].map({True: \"🔴 Anomaly\", False: \"🟢 Normal\"})\n",
    "st.line_chart(last_72.set_index(\"date\")[[\"temperature_2m\", \"expected_mean_temp\"]])\n",
    "\n",
    "st.divider()\n",
    "\n",
    "# --- Recent Anomalies Table ---\n",
    "st.subheader(\"🚨 Most Recent Anomalies\")\n",
    "anomalies = df[df[\"is_anomaly\"]].tail(20)[[\"date\", \"temperature_2m\", \"relative_humidity_2m\",\n",
    "                                            \"precipitation\", \"wind_speed_10m\",\n",
    "                                            \"anomaly_score_temp\", \"anomaly_score_precipitation\",\n",
    "                                            \"anomaly_score_wind_speed\"]].sort_values(\"date\", ascending=False)\n",
    "st.dataframe(anomalies, use_container_width=True)\n",
    "\n",
    "st.divider()\n",
    "\n",
    "# --- Monthly Anomaly Count ---\n",
    "st.subheader(\"📅 Anomalies by Month\")\n",
    "monthly = df[df[\"is_anomaly\"]].groupby(\"Month\").size().reset_index(name=\"count\")\n",
    "monthly[\"Month\"] = monthly[\"Month\"].map({1:\"Jan\",2:\"Feb\",3:\"Mar\",4:\"Apr\",5:\"May\",6:\"Jun\",\n",
    "                                          7:\"Jul\",8:\"Aug\",9:\"Sep\",10:\"Oct\",11:\"Nov\",12:\"Dec\"})\n",
    "st.bar_chart(monthly.set_index(\"Month\"))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c61ee02e-c9af-4c5b-9326-caf9e60ce159",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
